image: git.panter.ch:5001/panter/docker-build-images:ruby_2.5.1-yarn-firefox_beta

services:
  - postgres:9.4
  - node


variables:
  POSTGRES_DB: linkbox_test
  DISABLE_SPRING: 'true'
  TZ: Europe/Zurich
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"


cache:
  key: $CI_COMMIT_SHA
  untracked: true
  paths:
    - vendor/ruby
    - vendor
    - node_modules

before_script:
  - ls -A
  - ruby -v                                      # Print out ruby version for debugging
  - gem install bundler --no-ri --no-rdoc        # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor
  - yarn install

stages:
  - build
  - test

setup:
  stage: build
  variables:
    RAILS_ENV: test
  script:
    - ls -A
    - ruby -v                                      # Print out ruby version for debugging
    # If the cache would work, here could be the content of the before_script

.prepare_tests: &prepare_tests
  stage: test
  variables:
    RAILS_ENV: test

linting:
 <<: *prepare_tests
 script:
    - bin/fastcheck

rspec:
  <<: *prepare_tests
  script:
    - bundle exec rake db:schema:load
    - bundle exec rspec spec

reek:
  <<: *prepare_tests
  script:
    - bundle exec reek

brakeman:
  <<: *prepare_tests
  script:
    - bundle exec brakeman -q -z --summary > /dev/null

bundler-audit:
  <<: *prepare_tests
  script:
    - bundle exec bundler-audit
