---
detectors:
    Attribute:
      enabled: false
    NilCheck:
      enabled: false
    DuplicateMethodCall:
      max_calls: 2
    IrresponsibleModule:
      enabled: false

directories:
    "app/helpers":
      UtilityFunction:
        enabled: false
    "app/validators":
      UtilityFunction:
        enabled: false
    "app/controllers":
      IrresponsibleModule:
        enabled: false
      NestedIterators:
        max_allowed_nesting: 2
      UnusedPrivateMethod:
        enabled: false
      InstanceVariableAssumption:
        enabled: false
      UncommunicativeModuleName:
        accept:
        - "V1"
    "app/mailers":
      InstanceVariableAssumption:
        enabled: false

exclude_paths:
    - tmp
    - spec
    - vendor
    - log
    - coverage
    - bin
    - db/migrate
